{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fileflux.fullname" . }}
  labels:
    {{- include "fileflux.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: {{ include "fileflux.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "fileflux.fullname" . }}-backend
                port:
                  number: 3001
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "fileflux.fullname" . }}-backend
                port:
                  number: 3002
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fileflux.fullname" . }}-frontend
                port:
                  number: 80
{{- end }}
